# Generated by Django 5.2.8 on 2025-11-10 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setor', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('data_aquisicao', models.DateField()),
                ('responsavel', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='Em uso', max_length=30)),
                ('numero_patrimonio', models.CharField(max_length=9, unique=True)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='setor.setor')),
            ],
        ),
    ]
