# Generated by Django 5.2.8 on 2025-11-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='tipo',
            field=models.CharField(choices=[('desktop', 'Desktop'), ('notebook', 'Notebook'), ('monitor', 'Monitor'), ('servidor', 'Servidor'), ('nobreak', 'Nobreak'), ('impressora', 'Impressora'), ('outro', 'Outro')], default='outro', max_length=20),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='status',
            field=models.CharField(choices=[('em_uso', 'Em uso'), ('obsoleto', 'Obsoleto'), ('com_defeito', 'Com defeito')], default='Em uso', max_length=30),
        ),
    ]
