# Generated by Django 5.2.7 on 2025-11-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamento', '0002_equipamento_tipo_alter_equipamento_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
